### ISSUE TITLE
Status Bar Should not hover over contacts screen view on iOS

### ISSUE THREAD

**Issue by radusepe** [AwesomePossum446/Cordial#33]
![image](https://cloud.githubusercontent.com/assets/9058910/23084023/86400e2e-f52e-11e6-9bc5-42ac3cce9e0e.png)

**Comment by a1gemmel** [comment]
Looks like the profile images are also missing... and the radiusing on the text boxes isn't working. Yay for cross-platform compatibility

**Comment by radusepe** [comment]
Yeah I'll look into that

**Comment by a1gemmel** [comment]
You know I actually just remembered something relating to the top bar issue - when I was getting the text for the top tabs to float properly, setting it to 'center' had it looking like it was near the top of the button. I think it's behaving similarly on Android in that the view is clipping into the phone's top bar, but you can't tell on Android because the top bar renders on top of it.
