### ISSUE TITLE
UI for background color gradient

### ISSUE THREAD

**Issue by a1gemmel** [AwesomePossum446/Cordial#70]
We need a colorpicker UI for the user customizing the color gradient for the display background, and the card background. 

Or we drop the feature. Open to discussion here.

**Comment by radusepe** [comment]
I vote we drop the feature all together tbh. It feels ugly. If we just have a default profile picture and cover photo then users can upload whatever pictures they want rather than just picking some colors for a gradient. The gradient kind of takes away from the uniqueness of a card.
What are your thoughts on this?

**Comment by a1gemmel** [comment]
:100: Less features is good features :100:
